### ISSUE TITLE
Check why Thermotoga NrdJ is not included

### ISSUE THREAD

**Issue by erikrikarddaniel** [erikrikarddaniel/pfitmap-db#33]
Add data from GTDB run to test cases.

**Comment by GhadaNOUAIRIA** [comment]
Thermotoga's NrdJ exists in NrdJx.hmmout.gz but absent after classification.

**Comment by erikrikarddaniel** [comment]
It classifies to NrdJuc0.2 but only covers 0.8 of that profile. If `--hmm_mincov` is set to 0.8 or lower it's included.
