### ISSUE TITLE
Genomes with hmm hits but not included in feather files

### ISSUE THREAD

**Issue by GhadaNOUAIRIA** [erikrikarddaniel/pfitmap-db#37]
158 genomes were in all_genomes.faa files and have hits in hmmsearch/*.tblout files (housekeeping proteins and others Flavodoxin,: ex. GCA_001930175; thioredoxin: ex. GCA_000701865..).
More examples : GCA_003253435.1, GCA_003214255.1, GCA_000266865.1, GCA_001930545.1, GCA_001794205.1

**Comment by erikrikarddaniel** [comment]
I wonder if any of these have any hits that are in the hmm_profile_hierarchy.tsv. I see only radical SAMs and flavodoxins (we should perhaps have Flvd entries in hmm_profile_hierarchy.tsv.

**Comment by GhadaNOUAIRIA** [comment]
These genomes had no RNR hits (strange!) or others that were in hmm_profile_hierarchy.tsv, except for Flavodoxin, Thiodoxins... 
BUT, we have Flavodoxin_1 to Flavodoxin_5 profiles in hmm_profile_hierarchy.tsv + Flavodoxin_NrdI.

 N.B.: GCA_000266865.1 and GCA_001794205.1 have completeness of 60% or less.

**Comment by erikrikarddaniel** [comment]
I checked the two Flavodoxin_2 hits in GCA_001930175 and they are just too short (around 25% of the profile length). The RecA hit however is full length. I can't replicate this error so I'm closing this for the moment.

**Comment by GhadaNOUAIRIA** [comment]
The housekeeping profiles were not in hmm_profiles_hierarchy.tsv when we
did this run of the workflow. So RecA couldn't be in the classification.
